### ISSUE TITLE
Implement/complete elements from the "Text-level semantics" section.

### ISSUE THREAD

**Issue by DennisBirkholz** [Replum/framework#4]
Implement all elements and their specific attributes of the [Text-level semantics](https://www.w3.org/TR/html5/text-level-semantics.html#text-level-semantics) section of the HTML5 spec.

**Comment by tilmanbremer** [comment]
There seems to be a problem with the <br> element. At least it is throwing me an error when I try to use it. Any thoughts?

**Comment by DennisBirkholz** [comment]
Deleted comment from @tilmanbremer because I forgot to lock this issue (which is only meant as a task list for myself). If this problem persists, please create a separate issue with a meaningful error description. Thank you for participating!
